// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIfnAuwNzzw_oo8Qd8HlgsYIW4FKZNAEo',
    appId: '1:846765170681:web:1e1a4b84ebc0ce21af2728',
    messagingSenderId: '846765170681',
    projectId: 'pasteleria-v2',
    authDomain: 'pasteleria-v2.firebaseapp.com',
    storageBucket: 'pasteleria-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrOTC2cd31IDscFt8Qe5_Uo9xjZvD2fuE',
    appId: '1:846765170681:android:cba967d78861262eaf2728',
    messagingSenderId: '846765170681',
    projectId: 'pasteleria-v2',
    storageBucket: 'pasteleria-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5cokU5zSzgk5FBR5UrU_KnzldJgINdQ',
    appId: '1:846765170681:ios:9ceb2219c599812faf2728',
    messagingSenderId: '846765170681',
    projectId: 'pasteleria-v2',
    storageBucket: 'pasteleria-v2.firebasestorage.app',
    iosBundleId: 'com.example.pasteleriaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5cokU5zSzgk5FBR5UrU_KnzldJgINdQ',
    appId: '1:846765170681:ios:9ceb2219c599812faf2728',
    messagingSenderId: '846765170681',
    projectId: 'pasteleria-v2',
    storageBucket: 'pasteleria-v2.firebasestorage.app',
    iosBundleId: 'com.example.pasteleriaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIfnAuwNzzw_oo8Qd8HlgsYIW4FKZNAEo',
    appId: '1:846765170681:web:7ef1d05366760f38af2728',
    messagingSenderId: '846765170681',
    projectId: 'pasteleria-v2',
    authDomain: 'pasteleria-v2.firebaseapp.com',
    storageBucket: 'pasteleria-v2.firebasestorage.app',
  );
}
